"""Public API for the Prompt Regression Diagnosis reference core."""

from .canonical import canonical_json, content_hash, stable_id, to_primitive
from .errors import (
    BundleValidationError,
    MissingAblationFixtureError,
    PipelineInvariantError,
    PromptRegressionError,
)
from .model import (
    AblationPlan,
    AblationRun,
    AblationVariant,
    Dataset,
    DetectionConfig,
    DiagnosisReport,
    EvalResult,
    EvalRun,
    Evidence,
    EvidenceStance,
    FailureCluster,
    HypothesisStatus,
    MetricResult,
    PipelineDescriptor,
    Project,
    Prompt,
    PromptChange,
    PromptChangeType,
    PromptSegment,
    PromptVersion,
    Regression,
    RegressionBundle,
    RegressionCase,
    RegressionKind,
    RootCauseHypothesis,
    TestCase,
)
from .parsing import BUNDLE_SCHEMA_VERSION, load_bundle, loads_bundle, parse_bundle
from .pipeline import DiagnosisPipeline, REPORT_SCHEMA_VERSION
from .reporting import MarkdownReporter

__all__ = [
    "AblationPlan",
    "AblationRun",
    "AblationVariant",
    "BUNDLE_SCHEMA_VERSION",
    "BundleValidationError",
    "Dataset",
    "DetectionConfig",
    "DiagnosisPipeline",
    "DiagnosisReport",
    "EvalResult",
    "EvalRun",
    "Evidence",
    "EvidenceStance",
    "FailureCluster",
    "HypothesisStatus",
    "MarkdownReporter",
    "MetricResult",
    "MissingAblationFixtureError",
    "PipelineDescriptor",
    "PipelineInvariantError",
    "Project",
    "Prompt",
    "PromptChange",
    "PromptChangeType",
    "PromptRegressionError",
    "PromptSegment",
    "PromptVersion",
    "REPORT_SCHEMA_VERSION",
    "Regression",
    "RegressionBundle",
    "RegressionCase",
    "RegressionKind",
    "RootCauseHypothesis",
    "TestCase",
    "canonical_json",
    "content_hash",
    "load_bundle",
    "loads_bundle",
    "parse_bundle",
    "stable_id",
    "to_primitive",
]
