import {
  CANONICAL_BUNDLE_VERSION,
  DIAGNOSIS_REPORT_VERSION,
  type CanonicalRegressionBundle,
  type DiagnosisReport,
} from "./types";

export const canonicalBundleFixture: CanonicalRegressionBundle = {
  schema_version: CANONICAL_BUNDLE_VERSION,
  bundle_id: "bundle_checkout_v2",
  baseline: { prompt_version_id: "prompt-v1" },
  candidate: { prompt_version_id: "prompt-v2" },
};

export const diagnosisReportFixture: DiagnosisReport = {
  schema_version: DIAGNOSIS_REPORT_VERSION,
  report_id: "report-001",
  bundle_id: canonicalBundleFixture.bundle_id,
  input_bundle_hash: "sha256:fixture",
  generated_at: "2026-09-14T09:00:00.000Z",
  pipeline: {
    engine: "prompt-regression-core",
    engine_version: "0.1.0",
    config_hash: "sha256:config",
  },
  baseline_prompt_version_id: "prompt-v1",
  candidate_prompt_version_id: "prompt-v2",
  regression: {
    id: "regression-001",
    baseline_eval_run_id: "run-baseline",
    candidate_eval_run_id: "run-candidate",
    config_hash: "sha256:config",
    cases: [
      {
        id: "regression-case-001",
        test_case_id: "checkout-refund",
        kind: "hard_and_metric",
        baseline_passed: true,
        candidate_passed: false,
        metric_deltas: { correctness: -0.42 },
        primary_metric: "correctness",
      },
    ],
  },
  prompt_changes: [
    {
      id: "change-001",
      segment_id: "refund_policy",
      change_type: "rewritten",
      old_content: "退款前核验订单状态。",
      new_content: "尽快完成退款。",
      old_ordinal: 2,
      new_ordinal: 2,
      semantic_tags: ["约束弱化"],
      semantic_summary: "删除了退款前的订单状态核验要求。",
    },
  ],
  failure_clusters: [
    {
      id: "cluster-001",
      key: "correctness:refund",
      title: "退款规则被跳过",
      primary_metric: "correctness",
      regression_case_ids: ["regression-case-001"],
      test_case_ids: ["checkout-refund"],
      algorithm: "rule-based",
      algorithm_version: "1.0.0",
    },
  ],
  hypotheses: [
    {
      id: "hypothesis-supported",
      cluster_id: "cluster-001",
      prompt_change_ids: ["change-001"],
      mechanism: "删除核验约束后，模型过早执行退款。",
      expected_if_reverted: "恢复该区段后，退款用例应恢复且正常用例不受损。",
      prior_confidence: 0.82,
      verification_status: "supported",
    },
    {
      id: "hypothesis-pending",
      cluster_id: "cluster-001",
      prompt_change_ids: ["change-001"],
      mechanism: "措辞变短可能让模型忽略上下文。",
      expected_if_reverted: "恢复长措辞后，失败率可能下降。",
      prior_confidence: 0.35,
      verification_status: "hypothesized",
    },
  ],
  ablation_plans: [],
  ablation_variants: [],
  ablation_runs: [],
  evidence: [
    {
      id: "evidence-001",
      hypothesis_id: "hypothesis-supported",
      cluster_id: "cluster-001",
      prompt_change_ids: ["change-001"],
      ablation_run_id: "ablation-run-001",
      metric_key: "correctness",
      stance: "supporting",
      resulting_status: "supported",
      target_case_ids: ["checkout-refund", "checkout-refund-edge"],
      control_case_ids: ["checkout-order-status", "checkout-address"],
      target_mean_delta: 0.38,
      control_mean_delta: -0.01,
      max_observed_control_damage: 0.04,
      recovery_ratio: 0.9,
      target_sample_size: 2,
      control_sample_size: 2,
      unrecovered_hard_targets: 1,
      new_control_failures: 2,
      rationale: "目标用例大幅恢复，但仍需处理一个硬回归和两个新对照失败。",
    },
  ],
  recommendations: ["恢复退款核验区段后，使用相同配置重新评测。"],
};
